Update readme
sabrina-s/MondayClone pull request #2
Opened 2017-05-30 07:55 UTC by wlteo

Wrote some documentation

2017-05-30 09:51 UTC, sabrina-s requested changes
Just one typo, the rest is good to go! 😸

2017-05-30 09:51 UTC, sabrina-s commented on README.md
> +* Hat tip to anyone who's code was used
*whose 🤓

2017-05-30 09:53 UTC, wlteo commented on README.md
> +* Hat tip to anyone who's code was used
whoops

2017-05-31 02:01 UTC, sabrina-s approved these changes
LGTM! 🚀

2017-05-31 02:06 UTC, merged