Add username field in user registration page
sabrina-s/MondayClone pull request #3
Opened 2017-05-30 09:44 UTC by wlteo

Added username field for user registration page

2017-05-30 09:56 UTC, sabrina-s requested changes

2017-05-30 09:56 UTC, sabrina-s commented on app/views/devise/registrations/new.html.erb
> +    <%= f.email_field :username, autofocus: true %>
Should be f.text_field

2017-05-30 09:56 UTC, sabrina-s commented on app/views/devise/registrations/new.html.erb
>      <%= f.email_field :email, autofocus: true %>
I think we can remove the autofocus here.

2017-05-31 02:02 UTC, wlteo commented on app/views/devise/registrations/new.html.erb
>      <%= f.email_field :email, autofocus: true %>
Done!

2017-05-31 02:06 UTC, sabrina-s approved these changes
LGTM! 👍

2017-05-31 02:07 UTC, merged